version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

    volumes:
      - /mnt/mongo_data:/data/db
    networks:
      - app-network

  express:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "${PORT_API}:${PORT_API}"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT_API=${PORT_API}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    networks:
      - app-network
    depends_on:
      - mongo

networks:
  app-network:
    driver: bridge
